export const actions = {
  LIST_TODO_ITEMS: 'LIST_TODO_ITEMS',
  LIST_TODO_ITEMS_SUCCESS: 'LIST_TODO_ITEMS_SUCCESS',
  LIST_TODO_ITEMS_FAILED: 'LIST_TODO_ITEMS_FAILED',
  ADD_TODO_ITEM: 'ADD_TODO_ITEM',
  ADD_TODO_ITEM_SUCCESS: 'ADD_TODO_ITEM_SUCCESS',
  ADD_TODO_ITEM_FAILED: 'ADD_TODO_ITEM_FAILED',
  UPDATE_TODO_ITEM: 'UPDATE_TODO_ITEM',
  UPDATE_TODO_ITEM_SUCCESS: 'UPDATE_TODO_ITEM_SUCCESS',
  UPDATE_TODO_ITEM_FAILED: 'UPDATE_TODO_ITEM_FAILED'
}